"""Helper for retrieving captions from video_bench caption JSON files."""

from __future__ import annotations

import json
from enum import Enum
from pathlib import Path
from typing import Any


class MODE(str, Enum):
    """Supported caption retrieval modes."""

    IMAGE_BASED = "IMAGE_BASED"
    VIDEO_BASED = "VIDEO_BASED"


def _to_milliseconds(timestamp: float | int | str) -> float:
    """Normalize a timestamp to milliseconds.

    Numeric values are interpreted as milliseconds (matching the
    ``timestamp_ms`` field stored in captions.json). Strings are parsed
    as ``HH:MM:SS.mmm`` (the ``timestamp`` field format).
    """
    if isinstance(timestamp, bool):
        raise TypeError(
            "Timestamp must be a number (ms) or 'HH:MM:SS.mmm' string, got bool."
        )
    if isinstance(timestamp, (int, float)):
        return float(timestamp)
    if isinstance(timestamp, str):
        text = timestamp.strip()
        if not text:
            raise ValueError("Timestamp string must not be empty.")
        parts = text.split(":")
        if len(parts) != 3:
            raise ValueError(
                f"Timestamp string must follow 'HH:MM:SS.mmm', got: {timestamp!r}"
            )
        try:
            hours = float(parts[0])
            minutes = float(parts[1])
            seconds = float(parts[2])
        except ValueError as exc:
            raise ValueError(
                f"Timestamp string must follow 'HH:MM:SS.mmm', got: {timestamp!r}"
            ) from exc
        if minutes < 0 or minutes >= 60 or seconds < 0 or seconds >= 60:
            raise ValueError(
                f"Timestamp string has out-of-range minutes/seconds: {timestamp!r}"
            )
        return (hours * 3600 + minutes * 60 + seconds) * 1000
    raise TypeError(
        "Timestamp must be a number (ms) or 'HH:MM:SS.mmm' string, got "
        f"{type(timestamp).__name__}."
    )


def _load_json_file(path: Path) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Captions file is not valid JSON: {path}: {exc}") from exc

    if not isinstance(payload, dict):
        raise ValueError(f"Captions file must contain a JSON object: {path}")
    return payload


def _normalize_mode(mode: MODE | str) -> MODE:
    if isinstance(mode, MODE):
        return mode
    try:
        return MODE(mode)
    except ValueError as exc:
        valid_modes = ", ".join(item.value for item in MODE)
        raise ValueError(f"mode must be one of: {valid_modes}; got {mode!r}") from exc


def retrieve_captions(
    captions_dir: str | Path,
    video_name: str,
    start_timestamp: float | int | str,
    end_timestamp: float | int | str,
    mode: MODE | str,
) -> list[dict[str, Any]]:
    """Return captions from *captions_dir* within the given time range.

    In ``MODE.IMAGE_BASED``, ``captions_dir / "captions.json"`` is expected to
    follow the video_bench captions format, e.g.
    ``input/airport_walk/airport_walk_normal_meta/captions.json``::

        {
          "type": "video_bench_captions",
          "version": 1,
          "video_name": "airport_walk_normal.mov",
          "captions": [
            {
              "frame_index": 0,
              "timestamp_ms": 0,
              "timestamp": "00:00:00.000",
              "caption": "..."
            },
            ...
          ]
        }

    In ``MODE.VIDEO_BASED``, every matching-prefix ``*.json`` file under
    ``captions_dir`` and its subdirectories is expected to follow the segment
    annotation format generated by ``segment_and_caption_pipeline.py``. Segment
    annotation files whose ``[start_time_sec, end_time_sec]`` overlaps the
    requested range are returned.

    Parameters
    ----------
    captions_dir:
        Directory containing caption JSON files. For image-based mode, this must
        contain ``captions.json``.
    video_name:
        Required video name. In video-based mode, only JSON files whose file
        names start with this value are considered.
    start_timestamp:
        Lower bound of the time range. Either a number of milliseconds or an
        ``HH:MM:SS.mmm`` string.
    end_timestamp:
        Upper bound of the time range. Either a number of milliseconds or an
        ``HH:MM:SS.mmm`` string.
    mode:
        ``MODE.IMAGE_BASED`` or ``MODE.VIDEO_BASED``.

    Returns
    -------
    list[dict[str, Any]]
        The caption entries within the requested time range.

    Raises
    ------
    FileNotFoundError
        If ``captions_dir`` does not exist, or if image-based mode cannot find
        ``captions.json``.
    ValueError
        If a caption file is not valid JSON, is not in the expected format, if
        ``video_name`` or ``mode`` is invalid, or if ``start_timestamp`` is
        greater than ``end_timestamp``.
    TypeError
        If a timestamp is neither a number nor a string.
    """
    if not isinstance(video_name, str):
        raise TypeError(
            f"video_name must be a string, got {type(video_name).__name__}."
        )
    if not video_name:
        raise ValueError("video_name must not be empty.")

    normalized_mode = _normalize_mode(mode)
    start_ms = _to_milliseconds(start_timestamp)
    end_ms = _to_milliseconds(end_timestamp)
    if start_ms > end_ms:
        raise ValueError(
            f"start_timestamp ({start_ms} ms) must not be greater than "
            f"end_timestamp ({end_ms} ms)."
        )

    directory = Path(captions_dir)
    if not directory.is_dir():
        raise FileNotFoundError(f"Captions directory not found: {directory}")

    if normalized_mode is MODE.IMAGE_BASED:
        path = directory / "captions.json"
        if not path.is_file():
            raise FileNotFoundError(f"Captions file not found: {path}")

        payload = _load_json_file(path)
        captions = payload.get("captions")
        if not isinstance(captions, list):
            raise ValueError(f"Captions file is missing a 'captions' list: {path}")

        selected: list[dict[str, Any]] = []
        for entry in captions:
            if not isinstance(entry, dict):
                continue
            ts = entry.get("timestamp_ms")
            if not isinstance(ts, (int, float)) or isinstance(ts, bool):
                continue
            if start_ms <= float(ts) <= end_ms:
                selected.append(entry)
        return selected

    start_sec = start_ms / 1000
    end_sec = end_ms / 1000
    all_segments: dict[Any, dict[str, Any]] = {}
    for path in sorted(directory.rglob("*.json")):
        if not path.name.startswith(video_name):
            continue

        payload = _load_json_file(path)
        segment_start = payload.get("start_time_sec")
        segment_end = payload.get("end_time_sec")
        if (
            not isinstance(segment_start, (int, float))
            or isinstance(segment_start, bool)
            or not isinstance(segment_end, (int, float))
            or isinstance(segment_end, bool)
        ):
            raise ValueError(
                "Video-based caption file is missing numeric "
                f"'start_time_sec'/'end_time_sec': {path}"
            )
        if "annotation_raw" not in payload:
            raise ValueError(
                f"Video-based caption file is missing 'annotation_raw': {path}"
            )

        if float(segment_start) <= end_sec and start_sec <= float(segment_end):
            segment_key = payload.get("segment_index", path.as_posix())
            all_segments[segment_key] = payload
    return list(all_segments.values())
